Fix failing specs re: zip archive with nested entries
Fixes the following test failures:

```
zip files
  .list()
    when the archive file exists
      when the tree option is set to true
        it returns archive entries nested under their parent directory
          Expected 9 to be 2.
            at jasmine.Spec.<anonymous> (C:\projects\node-ls-archive\spec\zip-spec.coffee:43:33)
            at ontimeout (timers.js:498:11)
            at tryOnTimeout (timers.js:323:5)
          TypeError: Cannot read property 'getName' of undefined
            at jasmine.Spec.<anonymous> (C:\projects\node-ls-archive\spec\zip-spec.coffee:46:40)
            at ontimeout (timers.js:498:11)
            at tryOnTimeout (timers.js:323:5)
```

Refs: https://ci.appveyor.com/project/Atom/node-ls-archive/build/8#L57